#!/usr/bin/env python3
"""
Generate template-loader-helper.ts with REAL templates embedded
"""

from pathlib import Path
import json

def escape_template(content):
    """Escape template content for TypeScript string."""
    # Use backticks for template literals, escape backticks and ${ in content
    content = content.replace('\\', '\\\\')
    content = content.replace('`', '\\`')
    content = content.replace('${', '\\${')
    return content

def generate_typescript_module():
    """Generate the TypeScript module with embedded templates."""
    
    base_dir = Path(__file__).parent
    template_dir = base_dir / 'templates' / 'email_cleaned'
    
    # Templates needed for workflow
    template_files = [
        'email_notifica_info.html',
        'email_documenti_informativi.html',
        'email_invio_contratto.html',
        'email_invio_proforma.html',
        'email_benvenuto.html',
        'email_conferma.html',
        'email_conferma_attivazione.html',
    ]
    
    templates = {}
    
    print("📧 Loading templates...")
    for filename in template_files:
        filepath = template_dir / filename
        if not filepath.exists():
            print(f"  ⚠️  Missing: {filename}")
            continue
        
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Get template name without extension
        template_name = filename.replace('.html', '')
        templates[template_name] = escape_template(content)
        print(f"  ✅ Loaded: {template_name} ({len(content)} chars)")
    
    # Generate TypeScript code
    ts_code = '''/**
 * Email Template Loader Helper
 * 
 * This module provides email templates for the TeleMedCare workflow.
 * Templates are embedded directly in the code for Cloudflare Workers compatibility.
 * 
 * IMPORTANT: These templates are the REAL templates from /templates/email_cleaned/
 * with proper encoding fixes applied. Do NOT modify these manually!
 * 
 * To update templates:
 * 1. Edit files in /templates/email/
 * 2. Run: python3 fix_templates_final.py
 * 3. Run: python3 generate_template_loader.py
 * 4. Rebuild the application
 * 
 * Generated: Auto-generated by generate_template_loader.py
 */

// Template storage
const TEMPLATES: Record<string, string> = {
'''
    
    # Add each template
    for name, content in templates.items():
        ts_code += f'  "{name}": `{content}`,\n\n'
    
    ts_code += '''}

/**
 * Load an email template by name
 * @param templateName - Name of the template (without .html extension)
 * @returns Promise<string> - The template HTML content
 */
export async function loadEmailTemplate(templateName: string): Promise<string> {
  const template = TEMPLATES[templateName]
  
  if (!template) {
    console.error(`❌ Template not found: ${templateName}`)
    console.log(`Available templates: ${Object.keys(TEMPLATES).join(', ')}`)
    throw new Error(`Template "${templateName}" not found`)
  }
  
  console.log(`📧 [TEMPLATE] Loaded: ${templateName} (${template.length} chars)`)
  return template
}

/**
 * Render a template with data by replacing {{PLACEHOLDER}} patterns
 * @param template - The HTML template string
 * @param data - Object with key-value pairs for replacement
 * @returns string - Rendered HTML
 */
export function renderTemplate(template: string, data: Record<string, any>): string {
  let rendered = template
  
  // Replace all {{PLACEHOLDER}} patterns
  for (const [key, value] of Object.entries(data)) {
    const placeholder = `{{${key}}}`
    const stringValue = value !== null && value !== undefined ? String(value) : ''
    rendered = rendered.replaceAll(placeholder, stringValue)
  }
  
  // Log any remaining unreplaced placeholders
  const unreplaced = rendered.match(/{{[A-Z_]+}}/g)
  if (unreplaced && unreplaced.length > 0) {
    console.warn(`⚠️  Unreplaced placeholders: ${unreplaced.join(', ')}`)
  }
  
  return rendered
}

/**
 * Get list of available template names
 * @returns string[] - Array of template names
 */
export function getAvailableTemplates(): string[] {
  return Object.keys(TEMPLATES)
}

/**
 * Check if a template exists
 * @param templateName - Name of the template to check
 * @returns boolean - True if template exists
 */
export function templateExists(templateName: string): boolean {
  return templateName in TEMPLATES
}
'''
    
    return ts_code

def main():
    """Main function."""
    print("\n🔧 Generating template-loader-helper.ts...\n")
    
    ts_code = generate_typescript_module()
    
    output_file = Path(__file__).parent / 'src' / 'modules' / 'template-loader-helper.ts'
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(ts_code)
    
    print(f"\n{'='*60}")
    print(f"✅ Generated: {output_file}")
    print(f"📦 File size: {len(ts_code):,} bytes")
    print(f"{'='*60}\n")

if __name__ == '__main__':
    main()
